######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 21 12:43:04 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ghost.h Pacman.h PacmanBoard.h PacmanWindow.h auxiliaryFunctions.cpp
SOURCES += auxiliaryFunctions.cpp main.cpp PacmanBoard.cpp PacmanWindow.cpp
